BITRIX_ACTION_EQUIPPED = 'equipped'
BITRIX_ACTION_DELIVERY = 'delivery'
BITRIX_ACTION_WAITING_FOR_SUPPLY = 'waiting_for_supply'
BITRIX_ACTION_RESERVED = 'reserved'

BITRIX_BOOL_FIELD_TRUE = 'Y'
BITRIX_BOOL_FIELD_FALSE = 'N'


