# photos fields aliases
DEAL_BIG_PHOTO_ALIAS = 'UF_CRM_1583348851496'  # Фото заказа (большое)
DEAL_CHECKLIST_PHOTO_ALIAS = 'UF_CRM_1587838059218'  # Фото чеклиста (бумажный)
DEAL_RESERVE_PHOTO_ALIAS = 'UF_CRM_1620936565099'  # Резерв товара, фото


WEBHOOK_DEAL_ID_ALIAS = 'deal_id'
WEBHOOK_DEAL_FLORIST_ALIAS = 'florist'
WEBHOOK_DEAL_RESPONSIBLE_ALIAS = 'responsible'
WEBHOOK_DEAL_ORDER_ALIAS = 'order'
WEBHOOK_DEAL_COURIER_ALIAS = 'courier'
WEBHOOK_SECRET_ALIAS = 'secret'
WEBHOOK_ACCEPTED_ALIAS = 'accepted'
WEBHOOK_ACTION_ALIAS = 'action'
WEBHOOK_SUM_ALIAS = 'sum'
WEBHOOK_DATE_ALIAS = 'date'
WEBHOOK_TIME_ALIAS = 'time'
WEBHOOK_TYPE_ALIAS = 'type'
WEBHOOK_DEAL_SITE_LINK_ALIAS = 'link'
WEBHOOK_IS_RESERVED_ALIAS = 'is_reserved'
WEBHOOK_RESERVED_STR_ALIAS = 'reserved_str'
WEBHOOK_SUPPLY_DATE_ALIAS = 'supply_date'
WEBHOOK_DELIVERY_COMMENT_ALIAS = 'delivery_comment'
WEBHOOK_DELIVERY_TYPE_ALIAS = 'delivery_type'
WEBHOOK_SUBDIVISION_ALIAS = 'subdivision'


