DEAL_BIG_PHOTO_ALIAS = 'UF_CRM_1583348851496'


WEBHOOK_DEAL_ID_ALIAS = 'deal_id'
WEBHOOK_DEAL_FLORIST_ALIAS = 'florist'
WEBHOOK_DEAL_RESPONSIBLE_ALIAS = 'responsible'
WEBHOOK_DEAL_ORDER_ALIAS = 'order'
WEBHOOK_DEAL_COURIER_ALIAS = 'courier'
WEBHOOK_SECRET_ALIAS = 'secret'
WEBHOOK_ACCEPTED_ALIAS = 'accepted'
