BITRIX_ACTION_EQUIPPED = 'equipped'
BITRIX_ACTION_DELIVERY = 'delivery'
BITRIX_ACTION_WAITING_FOR_SUPPLY = 'waiting_for_supply'
BITRIX_ACTION_RESERVED = 'reserved'

DEAL_IS_RESERVED_YES = 'Да'
DEAL_IS_RESERVED_NO = 'Нет'



